language: rust
rust:
  - 1.0.0
  - 1.1.0
  - 1.2.0
  - 1.3.0
  - 1.4.0
  - stable
  - beta
  - nightly
sudo: false
before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
script:
  - cargo build --verbose
  - ([ $TRAVIS_RUST_VERSION != nightly ] || cargo build --verbose --features nightly)
  - cargo test --verbose
  - ([ $TRAVIS_RUST_VERSION != nightly ] || cargo test --verbose --features nightly)
  - ([ $TRAVIS_RUST_VERSION != nightly ] || cargo doc --no-deps --features nightly)
after_success:
  - travis-cargo --only nightly doc-upload
env:
  global:
    secure: "BdDntVHSompN+Qxz5Rz45VI4ZqhD72r6aPl166FADlnkIwS6N6FLWdqs51O7G5CpoMXEDvyYrjmRMZe/GYLIG9cmqmn/wUrWPO+PauGiIuG/D2dmfuUNvSTRcIe7UQLXrfP3yyfZPgqsH6pSnNEVopquQKy3KjzqepgriOJtbyY="



notifications:
  email:
    on_success: never
