
    - rust: nightly
      script:
        - cargo test
        - cargo test --features nightly
        - cargo test --manifest-path rand-derive/Cargo.toml
        - cargo doc --no-deps --features nightly
script:
  - cargo test
  - cargo test --manifest-path rand-derive/Cargo.toml
after_success:
  - travis-cargo --only nightly doc-upload
env:
  global:
    secure: "BdDntVHSompN+Qxz5Rz45VI4ZqhD72r6aPl166FADlnkIwS6N6FLWdqs51O7G5CpoMXEDvyYrjmRMZe/GYLIG9cmqmn/wUrWPO+PauGiIuG/D2dmfuUNvSTRcIe7UQLXrfP3yyfZPgqsH6pSnNEVopquQKy3KjzqepgriOJtbyY="

notifications:
  email:
    on_success: never
