[package]

name = "rand"
version = "0.3.9"
authors = ["The Rust Project Developers"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/rust-lang/rand"
documentation = "http://doc.rust-lang.org/rand"
homepage = "https://github.com/rust-lang/rand"
description = """
Random number generators and other randomness functionality.
"""
keywords = ["random"]

[dependencies]
libc = "0.1.1"

[target.x86_64-pc-windows-gnu.dependencies]
winapi = "0.2"
advapi32-sys = "0.1.2"

[target.x86_64-pc-windows-msvc.dependencies]
winapi = "0.2"
advapi32-sys = "0.1.2"

[target.i686-pc-windows-msvc]
winapi = "0.2"
advapi32-sys = "0.1.2"

[target.i686-pc-windows-gnu]
winapi = "0.2"
advapi32-sys = "0.1.2"

[dev-dependencies]
log = "0.3.0"
