[package]
name = "rand"
version = "0.4.2"
authors = ["The Rust Project Developers"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/rust-lang-nursery/rand"
documentation = "https://docs.rs/rand"
homepage = "https://github.com/rust-lang-nursery/rand"
description = """
Random number generators and other randomness functionality.
"""
keywords = ["random", "rng"]
categories = ["algorithms"]

[features]
default = ["std"]
nightly = ["i128_support"] # enables all features requiring nightly rust

std = ["libc", "winapi"] # default feature; without this rand uses libcore
alloc = []  # enables Vec and Box support without std

i128_support = [] # enables i128 and u128 support

serde-1 = ["serde", "serde_derive"]


[target.'cfg(unix)'.dependencies]
libc = { version = "0.2", optional = true }

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["minwindef", "ntsecapi", "profileapi", "winnt"], optional = true }

[dependencies]
log = { version = "0.4", optional = true }

serde = {version="1",optional=true}
serde_derive = {version="1", optional=true}

[dev-dependencies]
# This is for testing serde, unfortunately
# we can't specify feature-gated dev deps yet,
# see: https://github.com/rust-lang/cargo/issues/1596
bincode = "0.9"

[target.'cfg(target_os = "cloudabi")'.dependencies]
cloudabi = "0.0.3"

[target.'cfg(target_os = "fuchsia")'.dependencies]
fuchsia-zircon = "0.3.2"
