[package]
name = "rand"
version = "0.4.1"
authors = ["The Rust Project Developers"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/rust-lang-nursery/rand"
documentation = "https://docs.rs/rand"
homepage = "https://github.com/rust-lang-nursery/rand"
description = """
Random number generators and other randomness functionality.
"""
keywords = ["random", "rng"]
categories = ["algorithms"]

[features]
default = ["std"]
nightly = ["i128_support"] # enables all features requiring nightly rust

std = ["rand_core/std", "libc"] # default feature; without this rand uses libcore
alloc = []  # enables Vec and Box support without std

i128_support = ["rand_core/i128_support"] # enables i128 and u128 support

[dependencies]
# All deps must not use 'std' by default
rand_core = { path = 'rand_core', default-features = false }

[target.'cfg(unix)'.dependencies]
libc = { version = "0.2", optional = true }

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["minwindef", "ntsecapi", "profileapi", "winnt"] }

[workspace]
members = ["rand_core"]

[target.'cfg(target_os = "fuchsia")'.dependencies]
fuchsia-zircon = "0.3"
