[package]
name = "rand"
version = "0.4.0-pre.0"
authors = ["The Rust Project Developers"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/rust-lang-nursery/rand"
documentation = "https://docs.rs/rand"
homepage = "https://github.com/rust-lang-nursery/rand"
description = """
Random number generators and other randomness functionality.
"""
keywords = ["random", "rng"]
categories = ["algorithms"]

[features]
bound = []         # std::collections is unstable in 1.0.0
duration = []      # Duration is unstable in 1.0.0
ip_addr = []       # IpAddr is unstable in 1.0.0
i128_support = []  # unstable in current stable
nightly = ["bound", "duration", "i128_support", "ip_addr"]

[dependencies]
libc = "0.2"

[dev-dependencies]
log = "0.3.0"

[workspace]
members = ["rand-derive"]

[target.'cfg(target_os = "fuchsia")'.dependencies]
fuchsia-zircon = "0.3"
