[package]

name = "rand"
version = "0.3.15"
authors = ["The Rust Project Developers"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/rust-lang/rand"
documentation = "https://doc.rust-lang.org/rand"
homepage = "https://github.com/rust-lang/rand"
description = """
Random number generators and other randomness functionality.
"""
keywords = ["random", "rng"]
categories = ["algorithms"]

[features]
bound = []         # std::collections is unstable in 1.0.0
duration = []      # Duration is unstable in 1.0.0
ip_addr = []       # IpAddr is unstable in 1.0.0
i128_support = []  # unstable in current stable
nightly = ["bound", "duration", "i128_support", "ip_addr"]

[dependencies]
libc = "0.2"

[dev-dependencies]
log = "0.3.0"
